version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4572:4572"
    volumes:
      - ".localstack/s3_init.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - ./localstack:/tmp/localstack
